### PR TITLE
Optimal interpolation

### PR DESCRIPTION
**Pull request by richardarsenault**
## Pull Request Checklist

- [X] I have run the `report_check_sums.py` script and committed the results to this branch.

## Description

* Addition of Optimal interpolation test data, zipped into a single file with checksum added to readme.

### CODE REVIEW

**Comment by richardarsenault** [comment]
Here I followed instructions and computed the md5 hash with the "report_check_sums.py" function for the OI_data.zip file and got the checksum as shown in readme.md. 

However, when trying to download it, I get: 

`ValueError: MD5 hash of downloaded file (1613d74d9660a1802c05ea0ab96d4689-OI_data.zip) does not match the known hash: expected md5:1ab72270023366d0410eb6972d1e2656 but got 301d549106206dc71ca7151d4dac84dd. Deleted download for safety. The downloaded file may have been corrupted or the known hash may be outdated.
`
Am I doing anything wrong? Only thing I can see is that I am creating the file in my Linux VM and uploading it here on the web browser through Windows. But this should not change the checksum...

**Comment by Zeitsperre** [comment]
@richardarsenault 

I don't think that should change anything, especially since the checksum is being derived from a compressed zip file (for text files it would be different). If `md5` doesn't work, we could try a different hashing algorithm?

**Comment by richardarsenault** [comment]
Solved, thanks @Zeitsperre !

Tests are passing with data downloaded from this branch. Once merged, I will be able to update the branch in xhydro/optimal_interpolation.

**Review by RondeauG — APPROVED** [review]
LGTM.

**Pull request merged**
